In [2]:
import pandas as pd

df = pd.read_csv('2020_Yellow_Taxi_Trip_Data_20240522.csv')

print(df.head())

/tmp/ipykernel_15232/469248703.py:4: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('2020_Yellow_Taxi_Trip_Data_20240522.csv')

   VendorID    tpep_pickup_datetime   tpep_dropoff_datetime  passenger_count  \
0       1.0  01/01/2020 12:28:15 AM  01/01/2020 12:33:03 AM              1.0
1       1.0  01/01/2020 12:35:39 AM  01/01/2020 12:43:04 AM              1.0
2       1.0  01/01/2020 12:47:41 AM  01/01/2020 12:53:52 AM              1.0
3       1.0  01/01/2020 12:55:23 AM  01/01/2020 01:00:14 AM              1.0
4       2.0  01/01/2020 12:01:58 AM  01/01/2020 12:04:16 AM              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0            1.2         1.0                  N           238           239
1            1.2         1.0                  N           239           238
2            0.6         1.0                  N           238           238
3            0.8         1.0                  N           238           151
4            0.0         1.0                  N           193           193

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0           1.0          6.0    3.0      0.5        1.47           0.0
1           1.0          7.0    3.0      0.5        1.50           0.0
2           1.0          6.0    3.0      0.5        1.00           0.0
3           1.0          5.5    0.5      0.5        1.36           0.0
4           2.0          3.5    0.5      0.5        0.00           0.0

   improvement_surcharge  total_amount  congestion_surcharge
0                    0.3         11.27                   2.5
1                    0.3         12.30                   2.5
2                    0.3         10.80                   2.5
3                    0.3          8.16                   0.0
4                    0.3          4.80                   0.0

In [5]:
cols = df.columns
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge'],
      dtype='object')

## VendorID
- **Column Description**: A code indicating the TPEP provider that provided the record.
- **Expected/Allowed Values**: 1=Creative Mobile Technologies, LLC; 2=VeriFone Inc.
- **Field Limitations**: None
- **Additional Notes**: None

## tpep_pickup_datetime
- **Column Description**: The date and time when the meter was engaged.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## tpep_dropoff_datetime
- **Column Description**: The date and time when the meter was disengaged.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## passenger_count
- **Column Description**: The number of passengers in the vehicle.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: This is a driver-entered value.

## trip_distance
- **Column Description**: The elapsed trip distance in miles reported by the taximeter.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## RatecodeID
- **Column Description**: The final rate code in effect at the end of the trip.
- **Expected/Allowed Values**: 1=Standard rate; 2=JFK; 3=Newark; 4=Nassau or Westchester; 5=Negotiated fare; 6=Group ride; 99=Null/unknown
- **Field Limitations**: None
- **Additional Notes**: None

## store_and_fwd_flag
- **Column Description**: This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server.
- **Expected/Allowed Values**: Y=store and forward trip; N=not a store and forward trip
- **Field Limitations**: None
- **Additional Notes**: None

## PULocationID
- **Column Description**: TLC Taxi Zone in which the taximeter was engaged
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## DOLocationID
- **Column Description**: TLC Taxi Zone in which the taximeter was disengaged
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## payment_type
- **Column Description**: A numeric code signifying how the passenger paid for the trip.
- **Expected/Allowed Values**: 1=Credit card; 2=Cash; 3=No charge; 4=Dispute; 5=Unknown; 6=Voided trip
- **Field Limitations**: None
- **Additional Notes**: None

## fare_amount
- **Column Description**: The time-and-distance fare calculated by the meter.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## extra
- **Column Description**: Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## mta_tax
- **Column Description**: $0.50 MTA tax that is automatically triggered based on the metered rate in use.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## tip_amount
- **Column Description**: Tip amount – This field is automatically populated for credit card tips. Cash tips are not included.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## tolls_amount
- **Column Description**: Total amount of all tolls paid during the trip.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## improvement_surcharge
- **Column Description**: $0.30 improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## total_amount
- **Column Description**: The total amount charged to passengers. Does not include cash tips.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## congestion_surcharge
- **Column Description**: This surcharge is $2.50 and is assessed on trips that begin, end, or travel through Manhattan south of 96th Street. This went into effect on January 2019.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

## airport_fee
- **Column Description**: $1.25 surcharge for trips to/from LaGuardia and JFK Airports. This went into effect in October 2020.
- **Expected/Allowed Values**: None
- **Field Limitations**: None
- **Additional Notes**: None

In [7]:
for col in cols:
    print(df[col].value_counts())

VendorID
2.0    15908366
1.0     7930565
Name: count, dtype: int64
tpep_pickup_datetime
01/09/2020 04:53:00 PM    21
01/09/2020 06:13:00 PM    20
01/06/2020 08:13:00 AM    20
02/28/2020 05:55:01 PM    18
01/09/2020 07:51:00 AM    18
                          ..
08/10/2020 11:06:01 PM     1
08/10/2020 11:01:20 PM     1
08/10/2020 11:32:32 PM     1
08/10/2020 11:09:06 PM     1
12/31/2020 11:12:48 PM     1
Name: count, Length: 11775710, dtype: int64
tpep_dropoff_datetime
01/12/2020 12:00:00 AM    69
01/11/2020 12:00:00 AM    67
02/23/2020 12:00:00 AM    64
01/03/2020 12:00:00 AM    59
01/06/2020 12:00:00 AM    58
                          ..
07/08/2020 03:53:51 PM     1
07/08/2020 03:44:18 PM     1
07/08/2020 03:31:38 PM     1
07/08/2020 03:10:34 PM     1
12/31/2020 11:24:51 PM     1
Name: count, Length: 11776107, dtype: int64
passenger_count
1.0    17511207
2.0     3349133
3.0      872658
5.0      751719
0.0      489379
6.0      474541
4.0      390094
7.0          91
8.0          58
9.0          51
Name: count, dtype: int64
trip_distance
0.90       433892
0.80       432745
1.00       427469
1.10       410849
0.70       409921
            ...
60.10           1
71.60           1
64.94           1
97.45           1
3361.53         1
Name: count, Length: 7375, dtype: int64
RatecodeID
1.0     23231466
2.0       428167
5.0       119962
3.0        39440
4.0        18581
99.0        1165
6.0          150
Name: count, dtype: int64
store_and_fwd_flag
N    23593672
Y      245259
Name: count, dtype: int64
PULocationID
237    1145399
236    1089578
161     946849
186     862318
162     831587
        ...
111         26
2           25
30          20
105         14
199         11
Name: count, Length: 262, dtype: int64
DOLocationID
236    1126413
237    1015488
161     843734
170     738633
141     686806
        ...
99         116
2           45
105         10
199          2
104          1
Name: count, Length: 263, dtype: int64
payment_type
1.0    17463663
2.0     6148430
3.0      144463
4.0       82360
5.0          15
Name: count, dtype: int64
fare_amount
 6.00      1297545
 6.50      1270981
 5.50      1261879
 7.00      1242551
 5.00      1172494
            ...
 74.77           1
 103.55          1
 86.82           1
 73.99           1
-21.15           1
Name: count, Length: 10301, dtype: int64
extra
0.00     10273246
2.50      4186979
0.50      3921266
1.00      3007275
3.00      1606324
           ...
2.92            1
0.54            1
55.79           1
2.89            1
0.88            1
Name: count, Length: 370, dtype: int64
mta_tax
 0.50         24369473
 0.00           188209
-0.50            90730
 3.30               42
 0.35               10
 0.32                8
 1.10                6
 3.00                3
 2.50                2
 30.80               2
 3.25                1
 1.15                1
 0.90                1
 2.80                1
 0.59                1
 500000.50           1
 1.30                1
 39.51               1
 0.83                1
 2.74                1
 18.49               1
 6.80                1
 1.54                1
 1.57                1
Name: count, dtype: int64
tip_amount
0.00      7368165
1.00      1373745
2.00       934703
2.75       481413
2.06       342562
           ...
52.39           1
54.04           1
43.23           1
115.28          1
82.08           1
Name: count, Length: 5196, dtype: int64
tolls_amount
0.00     23523287
6.12      1010816
2.80        18663
11.75       15332
12.24       14549
           ...
51.99           1
42.00           1
7.59            1
6.33            1
58.50           1
Name: count, Length: 1915, dtype: int64
improvement_surcharge
 0.3    24540132
-0.3       92463
 0.0       15904
Name: count, dtype: int64
total_amount
 9.80      478105
 10.30     475149
 9.30      472577
 10.80     460619
 8.80      447658
            ...
 111.71         1
 195.28         1
 172.86         1
 192.79         1
-42.75          1
Name: count, Length: 18161, dtype: int64
congestion_surcharge
 2.50    21884389
 0.00     2689771
-2.50       74016
 0.75         171
 2.75         134
 0.50           5
-0.75           4
 1.00           4
 1.50           2
 2.00           1
 0.80           1
 3.00           1
Name: count, dtype: int64